[package]
name = "int-enum"
version = "0.2.0"
authors = ["James Whaley <juicy66173@gmail.com>"]
description = "A procedural macro for conversion between integer and enum types."
license = "MIT"
readme = "README.md"

documentation = "https://docs.rs/int-enum"
homepage = "https://github.com/Juici/int-enum-rs"
repository = "https://github.com/Juici/int-enum-rs"

edition = "2018"

[workspace]
members = ["int-enum-impl"]

[features]
default = ["std"]
std = ["int-enum-impl/std"]
alloc = ["int-enum-impl/alloc"]
serialize = ["serde", "int-enum-impl/serialize"]
from = ["int-enum-impl/from"]

[dev-dependencies]
int-enum = { path = "./" }
rustversion = "1.0"
trybuild = "1.0"
serde_json = "1"
serde = "1"

[dependencies]
cfg-if = "0.1"
int-enum-impl = { version = "0.2", path = "int-enum-impl" }
serde = { version = "1", optional = true }
