[package]
name = "int-enum"
version = "0.5.0"
authors = ["Juici <juicy66173@gmail.com>"]
description = "A derive macro for conversion between integer and enum types."
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.60"

documentation = "https://docs.rs/int-enum"
repository = "https://github.com/Juici/int-enum-rs"

[features]
default = ["std"]

std = ["int-enum-impl/std"]

serde = ["dep:serde", "int-enum-impl/serde"]
convert = ["int-enum-impl/convert"]

[dependencies]
int-enum-impl = { version = "0.5", path = "impl" }

serde = { version = "1", optional = true }

[dev-dependencies]
rustversion = "1.0"
serde_json = "1"
trybuild = "1.0"

[workspace]
members = ["impl"]
